### ISSUE TITLE
get_public_key?What did I neglect,please?

### ISSUE THREAD

**Issue by paul-99** [rchain/pyrchain#62]
![6PJSHZ9X`8(U5G 09J~EB2E](https://user-images.githubusercontent.com/54625983/80224304-1a16f400-867c-11ea-8d81-e14a757cad2a.png)

**Comment by zsluedem** [comment]
@paul-99 You should pass the key object instead of str.
take a look at python.https://github.com/rchain/pyrchain/blob/master/examples/vault_example.py

**Comment by paul-99** [comment]
thanks,!!! o i get it and the transactions is Launchand and  the token is received. thanks for your job!!

**Comment by paul-99** [comment]
@zsluedem
