### ISSUE TITLE
how to show the privateKey please? it donot look like common

### ISSUE THREAD

**Issue by paul-99** [rchain/pyrchain#63]
![image](https://user-images.githubusercontent.com/54625983/80271222-d27e7f80-86f0-11ea-94e7-3dbf29a9b684.png)

**Comment by paul-99** [comment]
![image](https://user-images.githubusercontent.com/54625983/80271336-e5de1a80-86f1-11ea-98ae-41ae87c63a33.png)

**Comment by zsluedem** [comment]
PrivateKey.generate().to_hex()
https://github.com/rchain/pyrchain/blob/master/examples/keys_example.py

**Comment by paul-99** [comment]
@zsluedem oh yeah  you are so good, thanks, thanks

**Comment by zsluedem** [comment]
feel free to open if you still have question
