### ISSUE TITLE
Reading data output to deployId with exploratory-deploy

### ISSUE THREAD

**Issue by w2vy** [rchain/pyrchain#74]
I have successfully deployed and executed a contract that results in executing

deployId(`rho:rchain:deployId`) and then deployId!(["#define", "inboxURI", uri])
where uri has been set to a valid uri

I have performed a client.deploy()
It's on localhost so I also did a propose
I can do a client.find_deploy and find the block the deploy is in
What methods can I use to get the data.

I have tried client.get_data_at_deploy_id() 
I also have looked at https://developer.rchain.coop/rnode-api

**Comment by w2vy** [comment]
I have been able to use rnode-api to see that the deployed code is in a block, I have tried every api in there and I am left to think that the only place the ["#define", "inboxURI", "uri-encoded-name"] could be stored is the tuple space.

both explore-deploy and explore-deploy-by-block-hash require a term or rholang code to be run, I have looked at powerbox and can't see anything that will obviously let me find data with a deployid

i am missing something very simple

**Comment by zsluedem** [comment]
Please give me some time to verify this.

**Comment by zsluedem** [comment]
> I have been able to use rnode-api to see that the deployed code is in a block, I have tried every api in there and I am left to think that the only place the ["#define", "inboxURI", "uri-encoded-name"] could be stored is the tuple space.
> 
> both explore-deploy and explore-deploy-by-block-hash require a term or rholang code to be run, I have looked at powerbox and can't see anything that will obviously let me find data with a deployid
> 
> i am missing something very simple

@w2vy Sorry for the late reply. I think I mislead you in the discord channel. Currently the explore deploy can not do such a thing and only data-at-name can do this trick.

**Comment by zsluedem** [comment]
close this one because of no replies. Feel free to reopen it if you got any further questions.

**Comment by HiXiaozhe** [comment]
I'm having the same problem as w2vy during smart contract deployment, that is, after deploying and proposing the smart contract locally, how to get the data in the channel. I tried the 'data_at_name' method but it doesn't work. It could be because I am not using it correctly, can you give me some help?
